### ISSUE TITLE
workflows.refactor_workflows fails on subworkflows

### ISSUE THREAD

**Issue by braza2** [galaxyproject/bioblend#475] opened 2023-06-22 10:19 UTC
Hi,
when applying gi.workflows.refactor_workflow(wf_id, actions = [
    {"action_type": "upgrade_all_steps"}])
the tool versions in the subworkflows in the workflow will not be upgraded.

**Comment by nsoranzo** [comment] 2023-06-22 11:16
I think this is by design? Ping @simonbray

**Comment by braza2** [comment] 2023-06-22 12:08
Ok, is there any other way to upgrade workflows consisting of many subworkflows? Editing subworkflows to upgrade them, then opening the main workflow again to upgrade the subworkflow and doing this one by one for each subworkflow is becoming an overwhelming task 😢

**Comment by simonbray** [comment] 2023-06-22 13:23
@braza2 indeed, it's deliberate behaviour; if you want tools within a subworkflow to be updated, you need to create a new version of the workflow with the desired tool versions. This is how Planemo is doing it, if it helps you? https://github.com/galaxyproject/planemo/blob/6a56d97b7622609bdca5b5c77dd933e22d596145/planemo/autoupdate.py#L275

Maybe you could just perform the task with Planemo directly: https://planemo.readthedocs.io/en/latest/autoupdate.html#updating-workflows

**Comment by jancrichter** [comment] 2023-06-26 14:21
@simonbray 

Can you elaborate a bit on how planemo autoupdate is supposed to achieve updating the workflowincluding subworkflows? Applying it to the workflow on our galaxy instance using the external galaxy engine it does not find any updatable tool versions, even though there should be something update-worthy in the main workflow, as well as in subworkflows. Honestly, it responds so quickly, that I don't feel that it is actually trying. We can only use planemo autoupdate with "external galaxy" because it is not feasible to first install all needed tools from private and public tool shed into a locally started galaxy.

Maybe it helps if I explain a bit of our situation. 

1) We have a bunch of workflows, these use multiple subworkflows each. There is some overlap in which subworkflows are used in each workflow. 

2) We store the JSON representation of the workflows in our VCS and install them in Galaxy from there. Thus, the subworkflows are contained within the main workflows, but no instance of the subworkflows themselves exists in Galaxy.

3) When we go to upgrade a workflow we therefore cannot simply update the subworkflow once and then got to tell the "main" workflows to use the new version. Instead we either need to re-insert the subworkflow, or go to each subworkflow within each main workflow and upgrade it, then go back to the main workflow and update the subworkflow.

Maybe we are overlooking something critical that would make our lives easier, if so please do point it out :)

**Comment by jancrichter** [comment] 2023-06-26 21:46
Hi @simonbray,

sorry for skipping over the code you actually linked, my mistake. I was able to get the command to run correctly, but further testing shows that it appears to be ignoring tools installed from our private toolshed. When using the "Upgrade workflow" action through the workflow editor, this is not the case. 

Do you have any idea what could be causing this?

**Comment by simonbray** [comment] 2023-06-27 05:42
Hmm, that's intriguing, the front end is making the same API call as Planemo, see here: https://github.com/galaxyproject/galaxy/blob/bb65b07584faa5abf62f15a3ee3ff5dadd9b33e8/client/src/components/Workflow/Editor/Index.vue#L578

**Comment by jancrichter** [comment] 2023-06-28 11:33
Ok, meanwhile, I figured out the following:

Our workflows include tools from our private toolshed and from toolshed.g2.bx.psu.edu.

planemo auto-update *does* update *all* tools in the main workflow and all subworkflows, *if* there is an update-worthy tool from toolshed.g2.bx.psu.edu in there somewhere. If there isn't, all tools are skipped.

On the CLI it only reports about finding tools from toolshed.g2.bx.psu.edu:

Either, nothing is found:

![image](https://github.com/galaxyproject/bioblend/assets/40425803/f2337229-8dfd-48fc-8788-fd89c9014f64)

or only the tool from  toolshed.g2.bx.psu.edu is found and subsequently the upgrade is triggered

![image](https://github.com/galaxyproject/bioblend/assets/40425803/35c222dd-f316-4410-ab2b-e260bfb0bf31)

In both examples, out-of-date tools from our private toolshed were present in both main workflow and subworkflows.

So I guess the part that is failing is the checking, whether an update should be performed at all.

**Comment by mvdbeek** [comment] 2023-06-28 11:35
planemo is hardcoding the main toolshed in the tool install routine, I think that's the likely culprit

**Comment by jancrichter** [comment] 2023-06-28 11:44
Could that potentially be changed to inform itself from the .planemo.yml?

**Comment by mvdbeek** [comment] 2023-06-28 11:51
Probably yes

**Comment by mvdbeek** [comment] 2023-06-28 11:51
(but I'd just infer the TS based on the tool id)

**Comment by jancrichter** [comment] 2023-06-28 12:01
that's probably a better solution, yes.

**Comment by nsoranzo** [comment] 2023-06-28 20:22
Since this is now tracked on a Planemo issue, closing here.

**Closed by nsoranzo** 2023-06-28 20:22 UTC
